### ISSUE TITLE
Connections to MSSQL fail with encryption (solution in the comment)

### ISSUE THREAD

**Issue by zacanger** [astronomer/ap-airflow#136]
The issue seems to be with the version of pymssql included with either Airflow or these images. After a few days of poking around, we found a solution (thanks to [this question](https://stackoverflow.com/questions/28724427/can-pymssql-have-a-secure-connection-ssl-to-ms-sql-server)).

```dockerfile
FROM astronomerinc/ap-airflow:1.10.10-buster-onbuild
USER root
RUN apt-get update
RUN apt-get install -y \
      build-essential \
      freetds-bin \
      freetds-dev

RUN pip3 install Cython
RUN pip3 install --no-binary pymssql pymssql
```

I didn't put in a PR because I'm not sure if you'd want that backported to existing builds, or just wait until Airflow 2 is out (there's no issue with pyodbc).

**Comment by wolfier** [comment]
Wanted to comment that another customer had this same exact issue because they started required TLS 1.2. They ran across the same StackOverflow question applied the same fix. Astronomer is still discussing what to do for next steps.

This is the Dockerfile the customer used, which is very similar with the one you provided.

```Dockerfile
FROM astronomerinc/ap-airflow:1.10.5-buster

# freetds dependencies 
USER root 
RUN apt-get update 
RUN apt-get install -y \ 
freetds-bin \ 
build-essential \ 
freetds-dev

RUN pip install --no-binary pymssql pymssql 
```

**Comment by zacanger** [comment]
@wolfier the other customer might be the data engineer I've been working with, he said he'd put in a ticket about it through another channel :)

**Comment by zacanger** [comment]
The other customer might be a data engineer at my employeer, I think he was going to put in a ticket through an official support channel :)

**Comment by ashb** [comment]
@zacanger Do you know if there's anyway (without having a working MSSQL server setup) that we could test the fix actually works before we release it?

**Comment by zacanger** [comment]
@ashb Not that I can think of, but testing with the Linux container version of SQL Server might work well enough for the test case. <https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-bash>
