### ISSUE TITLE
error to run dev start 

### ISSUE THREAD

**Issue by inglopez89** [astronomer/ap-airflow#310]
When run dev start with dockerfile  image base quay.io/astronomer/ap-airflow:2.1.4-buster the image docker keeping restarting on ubuntu 20.04.3
![image](https://user-images.githubusercontent.com/43654634/135004359-2e521c5b-32bc-4be5-8556-b8742e9774db.png)

**Comment by inglopez89** [comment]
I solve this error unistall docker, docker compose and reinstall astronomer cli

**Comment by kaxil** [comment]
Please add logs, it is difficult to tell without actually looking at the logs
