### ISSUE TITLE
certificate of `https://pip.astronomer.io/simple/` is expired

### ISSUE THREAD

**Issue by JaeguKim** [astronomer/ap-airflow#402]
Hi, I'm using `astronomerinc/ap-airflow:2.1.3-3-buster` image. 
It seems certificate of `https://pip.astronomer.io/simple/` is expired.

![image](https://user-images.githubusercontent.com/22807942/149713182-176ad1c2-3c3d-4f43-b8fd-894d664d9f06.png)

**Comment by pgvishnuram** [comment]
This issue has been resolved .

**Comment by kaxil** [comment]
Thanks @pgvishnuram and @danielhoherd for fixing this
