### ISSUE TITLE
Release date of 2.3.3-buster-onbuild

### ISSUE THREAD

**Issue by Maksimov-Dmitry** [astronomer/ap-airflow#519]
Could you say when 2.3.3-buster-onbuild image will be available?
<img width="605" alt="image" src="https://user-images.githubusercontent.com/61335724/185810670-6d67e10f-1222-40ad-80c5-e9e2044f0643.png">
Since we have got such notification, we would like to update astronomer ASAP, but we need only buster version.

**Comment by jedcunningham** [comment]
Hi @Maksimov-Dmitry, sorry for the slow reply.

Our 2.3 images will only ever have a bullseye image. There are no plans to offer one for buster. If this causes you issues, please escalate through [Astronomer Support](https://support.astronomer.io).

Thanks!

**Comment by jedcunningham** [comment]
I just realized you may have just updated the version number in your dockerfile and you may not actually care about the distribution.

2.3 no longer has the distribution in the tag, so you'd want to use `2.3.4-1-onbuild` or `2.3.4-onbuild` instead.
